[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.6.7"

# Netlify fonksiyonları için yapılandırma
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["public/**"]

# CI/CD için yapılandırma
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# URL yönlendirmeleri
[[redirects]]
  from = "/socket.io/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Next.js SSR ve CSR
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Güvenlik headerları
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# WebSocket desteği için yapılandırma
[[plugins]]
  package = "@netlify/plugin-nextjs" 