[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.6.7"
  NEXT_FORCE_EDGE_IMAGES = "true"

# Netlify fonksiyonları için yapılandırma
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["public/**"]

# CI/CD için yapılandırma
[build.processing]
  skip_processing = true

# URL yönlendirmeleri
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Güvenlik headerları
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/*"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# WebSocket desteği için yapılandırma
[[plugins]]
  package = "@netlify/plugin-nextjs" 